### ISSUE TITLE
is there a possable make .html for show stats on obs

### ISSUE THREAD

**Issue by Onijima** [NOALBS/belabot#2]
like liveU_stat_bot show each connection on it
![image](https://github.com/NOALBS/belabot/assets/90558278/1dc79ce5-b453-4533-bb63-e672d747f5fe)
![eth0](https://github.com/NOALBS/belabot/assets/90558278/bb3f12c8-d0dd-4d10-917a-be5187fa5d30)
![eth2](https://github.com/NOALBS/belabot/assets/90558278/7ab1f3bd-2470-474a-bd61-426ef54e4689)
![usb0](https://github.com/NOALBS/belabot/assets/90558278/89e4260d-82dc-4380-9faf-bcedd76b35d3)
![wlan0](https://github.com/NOALBS/belabot/assets/90558278/4b204ab3-83a8-48a7-ae0d-083dd7985b6c)

**Comment by 715209** [comment]
Hi @Onijima ,

Did you figure out how to do it?
